name = "Quantum_Neural_Network_Classifiers"
uuid = "99f4cae6-d6e8-4d3e-8b4b-2e0f17a78ee6"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[compat]
Yao = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
